### ISSUE TITLE
every update all

### ISSUE THREAD

**Issue by brunocalado** [Daxiongmao87/navarens-name-maker#3]
Hi. Great job!

Every time I update all modules I receive this message: 

![image](https://user-images.githubusercontent.com/4999783/131129486-f4fc809e-0f72-4c4f-8e1b-ee0e603766a5.png)

Can you fix it?

**Comment by Daxiongmao87** [comment]
Thank you for reporting this, I noticed it as well.  I'll be fixing it in the next update.  Unfortunately due to work, DMing a new campaign, a and a new puppy (yay!), my time working on this has slowed for the time being.  But I will get to it when I can!

**Comment by Daxiongmao87** [comment]
@brunocalado could uninstall and reinstall, then try and see if "update all" still prompts you with this popup?

**Comment by brunocalado** [comment]
no

tks
